### ISSUE TITLE
User without car causes crash

### ISSUE THREAD

**Issue by IngridMorstrad** [IngridMorstrad/ShareCar#42]
Steps to reproduce:
1. Login as a user who doesn't own a car.
2. Add Trip
3. Fill in details (leave "car" blank)
4. Submit

Rails error page displayed.

**Comment by venkatesh920** [comment]
So a user has to own a car before he can create a trip?

**Comment by IngridMorstrad** [comment]
If we're supporting hikes, then a "dummy car" can be created on the fly, which will be owned by the creator of the trip. Not sure if that's the approach we want to take since there would be N "dummy cars" for N hikes.

**Comment by venkatesh920** [comment]
Hikes deserves its own controller. So we can forget about that for the moment.
