### ISSUE TITLE
FB Auth

### ISSUE THREAD

**Issue by IngridMorstrad** [IngridMorstrad/ShareCar#46]
Objective:
To allow users to log in to the app using Facebook.

Following https://richonrails.com/articles/facebook-authentication-in-ruby-on-rails

Changes to views:
As described in the link, except this line:
<%= link_to "Log out", log_out_path, action: "delete", id: "log_out" %>

Changes to models:
provider, uid, oauth_token, oauth_expires_at fields to be added to the User model. Having all the details stored will allow for easy changes later.

Changes to controllers:
In application controller, helper method current_user changed to
@current_user ||= User.find(cookies[:user_id]) if cookies[:user_id]

In sessions controller, change create:
def create
    user = User.from_omniauth(env["omniauth.auth"])
    if user
      session[:user_id] = user.id
      redirect_to root_path
    else
      ## current method
    end
  end

Changes to configuration:
Add
gem 'omniauth-facebook', '~> 1.4.1'
to the Gemfile

Create config/initializers/omniauth.rb as in the linked article.

cacert.perm placed in root folder.

routes.rb:
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

**Comment by venkatesh920** [comment]
In sessions_controller#create, you should use cookies[:user_id] = user.id.

Otherwise, it seems fine.

**Comment by IngridMorstrad** [comment]
Removed gem version from line:
gem 'omniauth-facebook', '~> 1.4.1'
as it was causing errors due to dependencies requiring different versions of a gem.

The view edited is main.html.erb and not application.html.erb.

**Comment by IngridMorstrad** [comment]
This feature is now present thanks to a few commits by @venkatesh920
